### ISSUE TITLE
执行pnpm run build:easyest 报gulp错误

### ISSUE THREAD

**Issue by duke-git** [qddidi/easyest#3]
gulp -v                                    
CLI version: 2.3.0
Local version: 4.0.2
参考下图：
![image](https://user-images.githubusercontent.com/5037603/228487732-c1298aef-b534-43cc-b727-07ddc1fb9411.png)

**Comment by qddidi** [comment]
我这边重新拉去取代码安装打包是没有复现你这个问题的,可否提供一个出现此问题可访问的git仓库我看一下

**Comment by duke-git** [comment]
> 我这边重新拉去取代码安装打包是没有复现你这个问题的,可否提供一个出现此问题可访问的git仓库我看一下

我拉取你的仓库[easyest](https://github.com/qddidi/easyest)然后在本地可以复现问题，我怀疑是@types/gulp问题，检查了本地gulp版本，本地gulp没有问题。
在gulp和@types/gulp也提了issue:

https://github.com/gulpjs/gulp/issues/2722
https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/64940
