### ISSUE TITLE
组件的全局提示没有

### ISSUE THREAD

**Issue by Triumph-light** [qddidi/easyest#7]
我创建了components.d.ts文件暴露给volar这个接口，同时在根目录下tsconfig.json里引入了后，packages/components里的其他地方都有提示并且在play里面的app.vue文件写也有语法提示，但是放在标签上面只有any类型，同时我查看了node_modules里面的对于这个组件库引用，发现里面却是any类型，不知道让中这个全局的类型提示起作用，希望博主能答疑一下。
我的GitHub项目地址：https://github.com/Triumph-light/EvoluCore

**Comment by qddidi** [comment]
components.d.ts文件中

```
import * as components from './index.ts';
```
修改为

```
import * as components from './index';
```

**Comment by Triumph-light** [comment]
还是不可以，移上去没有提示
